### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by cliftonlabrum** [thierryH91200/OutlineViewReorder#1]
This project has been invaluable in helping me understand `NSOutlineView`. It's hard to find a Swift example these days. Thank you very much! :)

**Comment by thierryH91200** [comment]
for @cliftonlabrum 
look at also 
https://github.com/thierryH91200/SideBarDemo/tree/master/SideBarDemo

it's a simple application with bubbles/badges it's under construction
easier to understand
